version: '3.5'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserver
    container_name: sqlserver
    ports:
        - "1433:1433"
    environment:
      SA_PASSWORD: Bubbles!123
      ACCEPT_EULA: Y
    volumes:
      - ./databases/sqlserver/data:/var/opt/mssql/data 
      - ./databases/sqlserver/log:/var/opt/mssql/log 
      - ./databases/sqlserver/secrets:/var/opt/mssql/secrets
    networks:
      - my-proxy-net

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Bubbles!123
    volumes:
      - ./databases/mongo/data/db:/data/db
    networks:
      - my-proxy-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8005:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Bubbles!123      
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: coble-up-net