version: '3.5'

services:
  kafka-setup:
    image: confluentinc/cp-kafka:5.1.1
    hostname: kafka-setup
    container_name: kafka-setup
    volumes:
     - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                       ping -c 1 kafka1 && \
                       ping -c 1 zoo1 && \
                       kafka-topics --create --if-not-exists --zookeeper zoo1:2181 --partitions 1 --replication-factor 1 --topic bubbles && \
                       echo Waiting 60 seconds for Connect to be ready... && \
                       sleep 60 && \
                       /tmp/dashboard/docker-combined.sh'"
    environment:
      # The following settings are listed here only to satisfy the image's requirements.
      # We override the image's `command` anyways, hence this container will not start a broker.
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: coble-up-net